### ISSUE TITLE
Refactor: makeReader API

### ISSUE THREAD

**Issue by mijamo911** [amzn/ion-js#10]
I think I made a goof while introducing type safety and made the argument to makeReader() a Span. Ideally users should just have some data (string, number[], Buffer, etc.) and be able to pass it directly into makeReader() - we should do all the heavy lifting on our part to wrangle it into the correct Span type

**Comment by pbcornell** [comment]
makeReader signature is now:
```javascript
function makeReader(buf: ReaderBuffer): Reader {
```
Closing.
