### ISSUE TITLE
Ion.ts does not export Reader / Writer

### ISSUE THREAD

**Issue by eyce9000** [amzn/ion-js#110]
I woud like to be able to use ion-js in typescript. However, the Reader and Writer are not exported from the main class, so I seem to be unable to import them.

For example the following code would not work:

```ts
import * as IonJS from 'ion-js';

export class IonStructParser {
  private ionReader: IonJS.Reader // Reader not exported
}
```

Apologies if there is an obvious solution to this, I am not very strong with the typescript module system

**Comment by wesboyt** [comment]
Hey eyce,
Right now the library is in alpha and has a number of bugs around state/containers, binary/text, etc.
Were actively working on fixing it up to the standards that our other libraries ascribe to!
The TextReader is exported during compiletime, You need to import the TextReader with a line like:
import { TextReader } from "./IonTextReader";
than you can instantiate a TextReader with new TextReader();


Alternatively TextReaders are available via the compiled ion.js file with the lines:
var ion = require("{REPO LOCATION}/ion-js/{compiled ion.js location}/Ion.js");
var reader = ion.makeReader(input);

**Comment by eyce9000** [comment]
The second approach seems to work. Thanks

**Comment by jamesdbowman** [comment]
Would it be possible to export `IonJS.Reader` and `IonJS.Writer` types now? Thanks!

**Comment by wesboyt** [comment]
Yes of course!
