### ISSUE TITLE
no support for bigints.ion

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#111]
Ints outside of javascripts floating point representation on an int are not supported currently.

-The value -0x8000000000000000 evaluates as NaN
-Larger values such as: 18173238162219679736857031944447898744767430095109316084451026048678348094928854458274167288816962557611640075817315237016025726423548207924331642028847993938530524659112028449811515920726159569583847554301932799584192974700038250645135419704389244690214111003505621818033044965879076306690914532152840279256440975668846810694285470204245958782248405612488959069641454132691581386219910938587286910894148564397155066367399697230287047229035630842240888106685623631032505806388903066971508775182055551847210338095961815021030725796281642316166745051164958432783938535334657296749823645911331793861360616240344479015948
return undefined.

**Comment by zslayton** [comment]
Fixed in #465.
