### ISSUE TITLE
numbers

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#123]
Binaryints are broken.  Ints/floats with underscores are unsupported.

**Comment by wesboyt** [comment]
The input:
12_34.56_78e0
produces the error:
Error: invalid character after number
After inspection there is no logic flow for skipping over underscores in the parser.

The input:
 -0b100
produces the error:
Error: invalid character after number
after inspection there is no logic around parsing binary numbers.

**Comment by pbcornell** [comment]
This isssue has been split into #239 and #240.  Closing.
