### ISSUE TITLE
triplequotes with chained escapes

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#126]
corrupt the parser state

**Comment by wesboyt** [comment]
The input:
[
  "\\",

  '''\\''',

  '''\\\
'''
]

[
  "'",

  '''\'''',

  ''''\
''',

  '''\
\''''
]
produces the error:
Error: invalid escape sequence

On further inspection the parser incorrectly increments over the whitespace between triplequotes as it reads chained escapes.

**Comment by tgregg** [comment]
Was there a copy/paste problem here? The first string "\" (on line 2) doesn't look valid. The backslash would escape the quote that follows, and the string wouldn't end before hitting a newline, which is invalid.

**Comment by wesboyt** [comment]
fixed in #153
