### ISSUE TITLE
Sexp parsing

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#158]
Sexp parsing has an error when reading operator symbols.
Assumes there is a whitespace gap between the first symbol and the operator symbol which is incorrect.
Need to alter the parser indexing logic flow between symbol reads to allow operator terminating characters.

(a--1)
roundtrips as:
(a a-- 1)
the readpastwhitespace function call is incorrectly being used and not changing the indexes as no whitespace is found.

**Comment by Boyettw** [comment]
fixed #159

**Comment by wesboyt** [comment]
Fixed #159
