### ISSUE TITLE
decimal precision incorrect (binary only?)

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#160]
123456.0 vs. 1234560.d-1
Offsets have not been set correctly effecting precision.

**Comment by pbcornell** [comment]
Is this issue only for binary?  or text? (previous title suggested it was only binary)

**Comment by pbcornell** [comment]
Per [these unit tests](https://github.com/amzn/ion-js/blob/42d14cd62bfc67bb8703e4402793fc738a9bb79f/tests/unit/IonDecimalTest.js#L54), coefficient and exponent are being correctly calculated.  Closing.
