### ISSUE TITLE
Binary Floats

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#161]
1230000000 turns into 0

**Comment by pbcornell** [comment]
maybe fixed already?

**Comment by zslayton** [comment]
[Unit tests](https://github.com/amzn/ion-js/blob/development/tests/unit/IonParserBinaryRawTest.js#L367-L383) added in PR #286 show that `IonParserBinaryRaw` reads `1230000000` correctly.

I'm leaving this open for the moment as
> 1230000000 turns into 0
probably describes a full round trip, so there may be an issue with the writing side of things.

**Comment by wesboyt** [comment]
The example is not an issue roundtrip either. float test vectors are working, non-equivs/floats.ion is failing due to the value 0x7ff0000000000000 which is a 64 bit integer and not related to this issue.
