### ISSUE TITLE
Cookbook

### ISSUE THREAD

**Issue by raganhan** [amzn/ion-js#168]
Create a cookbook with examples on how to use ion-js.

**Comment by anandharshan** [comment]
The docs seem very naive.  Only one examlple give is not working. 

Please add relevant example. Will make life easier

**Comment by wesboyt** [comment]
Agreed the documentation is truly lacking at this point. Unfortunately I am the only developer actively working on the project and am currently working on the binary format support. The binary support should be done fairly soon. 
If you have any specific text examples you'd like I can whip one up quite easily as the text side is full functional at this time.

**Comment by pbcornell** [comment]
The Ion [Cookbook](https://amzn.github.io/ion-docs/guides/cookbook.html) now contains JavaScript examples alongside the Java examples, where applicable.
