### ISSUE TITLE
Timestamp bug

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#180]
- illegal state - /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/timestamp/timestamp2011-02-20T19_30_59_100-08_00.10n (2ms)
- EventStream tests - Given February 29th but year 1935 is not a leap year
  at Timestamp.checkValid - /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/timestamp/leapDay.ion (10ms)

**Comment by pbcornell** [comment]
These files are no longer on any skiplists:
* good/timestamp/timestamp2011-02-20T19_30_59_100-08_00.10n
* good/timestamp/leapDay.ion

Closing.
