### ISSUE TITLE
binary writer incorrectly encodes the sign bit of some decimals

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#182]
- invalid integer - /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/testfile31.ion
- /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/equivs/symbols.ion

**Comment by pbcornell** [comment]
`symbols.ion` is no longer on a skiplist

`testfile31.ion` is failing binary write/read on the value `4000000000.`.

**Comment by wesboyt** [comment]
I'm also failing on -0. as well after my decimal fixes, gonna investigate further.

**Comment by pbcornell** [comment]
`testfile31.ion` removed from the skiplist by #281.  Any failures related to `-0` should be opened in a separate issue.  Closing.
