### ISSUE TITLE
eventstream failure:  good/intBigSize1201.10n (Int parsing as float?)

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#184]
- illegal float length - /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/intBigSize1201.10n

**Comment by zslayton** [comment]
> PASS: ion-tests/iontestdata/good/intBigSize1201.10n (23ms)

Closing this as the test is currently passing.

**Comment by wesboyt** [comment]
still bugged, were parsing ints over 32 bits of precision. We should be throwing on this file and add it to the skiplist until m5.

**Comment by wesboyt** [comment]
were currently throwing moving to m5

**Comment by pbcornell** [comment]
Since this issue was reopened, support for integers of arbitrary size has been added, and this file is passing.  Closing.
