### ISSUE TITLE
EventStreams unequal

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#186]
- /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/whitespace.ion
- /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/timestamp/timestamp2011-02.10n
- /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/testfile9.ion
 - /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/testfile8.ion
- /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/testfile6.ion
- /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/testfile26.ion
- /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/testfile24.ion
- /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/testfile23.ion
- /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/symbolWithSpecialWhitespace.ion
- /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/symbolWithDel.ion

**Comment by pbcornell** [comment]
Note that the list of files above is NOT comprehensive.

**Comment by pbcornell** [comment]
good/testfile9.ion has been addressed by #267

**Comment by pbcornell** [comment]
Of the list above, only the following two files are failing at this time:
* timestamp/timestamp2011-02.10n
    Error:  Streams unequal (the value's binary bytes differ)
* testfile23.ion
    Error: Attempted to read an unsigned int that was larger than 31 bits. Use readUnsignedLongIntFrom instead. UInt size: 4, value: -294967296
  at Function.readUnsignedIntFrom  <src/IonParserBinaryRaw.ts:252:18>
  at ParserBinaryRaw.readUnsignedInt  <src/IonParserBinaryRaw.ts:265:31>
  at ParserBinaryRaw.load_value  <src/IonParserBinaryRaw.ts:465:38>
  at ParserBinaryRaw.numberValue  <src/IonParserBinaryRaw.ts:606:10>
  at BinaryReader.numberValue  <src/IonBinaryReader.ts:192:24>
  at BinaryReader.value  <src/IonBinaryReader.ts:225:20>
  at IonEventStream.parseBinaryValue  <src/IonEventStream.ts:401:26>
  at IonEventStream.marshalEvent  <src/IonEventStream.ts:275:51>
  at IonEventStream.marshalStream  <src/IonEventStream.ts:219:48>
  at IonEventStream.generateStream  <src/IonEventStream.ts:167:17>

**Comment by pbcornell** [comment]
Created #282 and #283 to address the two remaining failures.  Closing this issue in favor of those two.
