### ISSUE TITLE
lst serialized incorrectly from binary writer

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#187]
throws within binary reader
- EventStream tests - /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/testfile8.ion (106ms)
Error: SymbolID greater than maxID.
  at BinaryReader.fieldName  </home/travis/build/amzn/ion-js/src/IonBinaryReader.ts:134:16>
  at Object.makeSymbolTable  </home/travis/build/amzn/ion-js/src/IonSymbols.ts:100:26>
  at BinaryReader.next

**Comment by pbcornell** [comment]
testfile8.ion is not on a skiplist, closing
