### ISSUE TITLE
binary writer serializes illegal utf8

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#188]
EventStream tests - /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/testfile7.ion (33ms)
Error: UTF-8 decode: unknown multibyte start 0x8f at index 0
  at Object.decodeUtf8  </home/travis/build/amzn/ion-
at Object.decodeUtf8  </home/travis/build/amzn/ion-js/src/IonUnicode.ts:64:25>
  at ParserBinaryRaw.read_string_value  </home/travis/build/amzn/ion-js/src/IonParserBinaryRaw.ts:274:15>

- /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/subfieldInt.ion
- /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/strings.ion (214ms)
Error: UTF-8 decode: incomplete 3-byte sequence

**Comment by zslayton** [comment]
Closing this as the `iontestdata/good/testfile7.ion` event stream test is currently passing.
