### ISSUE TITLE
Clob is not a string roundtrip

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#189]
- EventStream tests - /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/testfile28.10n (3ms)
TypeError: input.slice is not a function

**Comment by pbcornell** [comment]
`good/testfile28.10n` is not on any skiplist at this time; closing

**Comment by wesboyt** [comment]
this got fixed by https://github.com/amzn/ion-js/pull/251 unless im mistaken.
