### ISSUE TITLE
EventStream.writeIon() cant handle null containers

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#190]
- /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/testfile22.ion (39ms)
Error: unexpected type: list

**Comment by zslayton** [comment]
I checked in my local environment: `testfile22.ion` can be safely removed from the skip list. I'll leave this issue open until that change lands.

**Comment by wesboyt** [comment]
needs to PR reverted changes back in
