### ISSUE TITLE
Nan losing quotes roundtrip

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#196]
- /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/fieldNameQuotedNan.ion (13ms)
Error: can't use 'nan' as a fieldname without quotes
- /home/travis/build/amzn/ion-js/ion-tests/iontestdata/good/fieldNameQuotedFalse.ion

**Comment by pbcornell** [comment]
with #264, fieldNameQuotedNan.ion and fieldNameQuotedFalse.ion now pass, closing
