### ISSUE TITLE
unit test failure

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#197]
- Catalog - Find specific version returns undefined if specific version not found (4ms)
AssertionError: expected null to equal undefined
- Catalog - Find specific version returns undefined if any version not found (0ms)
TypeError: Cannot read property '2' of undefined
-  Catalog - Find latest version returns undefined if no version exists (0ms)
AssertionError: expected null to equal undefined
- Decimal - Parses 56.789 (1ms)
AssertionError: expected '578' to equal '56789'
- Decimal - Parses -1. (0ms)
Error: Invalid integer: .
- Decimal - Parses 123456000. (0ms)
AssertionError: expected 0 to equal 3
- Decimal - Strips trailing zeroes from 123456000 (0ms)
TypeError: ion.Decimal.stripTrailingZeroes is not a function
- Decimal - Mantissa-only decimal string has leading zero (0ms)
AssertionError: expected '12345dNaN' to equal '0.123456'
- Text Writer - Writes positive decimal (2ms)
AssertionError: 1245d-3 != 123.456: expected { '0': 49, '1': 50, '2': 52, '3': 53, '4': 100, '5': 45, '6': 51 } to deeply equal { '0': 49, '1': 50, '2': 51, '3': 46, '4': 52, '5': 53, '6': 54 }
  {"0": 49,"1": 50, "2": 51, "3": 46, "4": 52, "5": 53, "6": 54, "2": 52, "3": 53, "4": 100, "5": 45, "6": 51}

**Comment by pbcornell** [comment]
All the unit tests identified above are passing.  No work left to do here, closing.
