### ISSUE TITLE
RunKit link on README defaults to v2.1.3

### ISSUE THREAD

**Issue by mtcalvin** [amzn/ion-js#201]
On the README, there is a "Try it yourself" link, which links to https://npm.runkit.com/ion-js (this is also linked from the npm packge).

However, opening this link defaults to RunKit importing v2.1.3, which is an older, buggier version of ion-js (according to the README, the current version is 3.0.0-beta3).

Is it possible to get RunKit to import the latest supported version of ion-js instead of v2.1.3?

**Comment by wesboyt** [comment]
I spoke with the runkit team and they said as long as we are tagging revisions as beta their system will not update. So we could do so but it might be confusing for consumers in npm

**Comment by mtcalvin** [comment]
If it can't be forced to resolve to the new version, should we just remove that link?  Or should the old version be marked as deprecated in npm?

It's creating confusion -- I had another developer look at IonJS and they came back to tell me it was broken in ways that I know have already been fixed, and only once I had them show me in RunKit did we realize it was loading an old version.

**Comment by wesboyt** [comment]
Im about to push a new revision with typescript readers/writer classes exported. I can remove the beta revision tag and it will reflect the changes.

**Comment by raganhan** [comment]
#207 tries to clarify this until we have a stable 3.x version

**Comment by wesboyt** [comment]
fixed: https://github.com/amzn/ion-js/pull/488
