### ISSUE TITLE
Reading binary UInt is broken for values requiring exactly 32 bits

### ISSUE THREAD

**Issue by zslayton** [amzn/ion-js#210]
Discovered while working on #209, part of #205.

Javascript's bitwise operators [convert their operands into 32-bit *signed* integers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators#Signed_32-bit_integers). This means that we can only store unsigned values using up to 31 bits (inclusive) in each `number` value.

`ParserBinaryRaw::load_value` will call `readUnsignedLongInt()` if the `_len` value is > 4, which covers all numbers needing more than 32 bits. We need a special case for reading unsigned integer values where `_len` is 4, but the first byte (which we can `peek()` at before officially reading it) is >127, requiring the highest bit to be set. This will allow us to call `readUnsignedLongInt()` on values which require exactly 32 bits.

**Comment by pbcornell** [comment]
We believe this is fixed, closing

**Comment by zslayton** [comment]
Closed by #355.
