### ISSUE TITLE
Reading a signed integer modifies the input bytes being read

### ISSUE THREAD

**Issue by zslayton** [amzn/ion-js#217]
When reading a signed integer, `ParserBinaryRaw::readLongInt` [overwrites a byte in the input stream](https://github.com/amzn/ion-js/blob/development/src/IonParserBinaryRaw.ts#L216). This is done to simplify the process of calling `LongInt.fromIntBytes`, however:
* It's destructive--the same Ion bytes cannot be read twice with an `IonReader`.
* `LongInt.fromIntBytes` expects an `Array` of `Number`s, so our `Uint8Array` [has to be cloned anyway](https://github.com/amzn/ion-js/blob/development/src/IonParserBinaryRaw.ts#L217). We might as well modify the first `Number` in the new version of the data.

Related to #205 and #212.

**Comment by wesboyt** [comment]
Makes sense to me! Pretty gnarly bug.

**Comment by zslayton** [comment]
Closed by #222.
