### ISSUE TITLE
Signed integers are always stored as BigIntegers

### ISSUE THREAD

**Issue by zslayton** [amzn/ion-js#218]
All data types requiring a signed int of a known size (namely `Timestamp` and `Decimal`) currently call [`ParserBinaryRaw::readLongInt`](https://github.com/amzn/ion-js/blob/development/src/IonParserBinaryRaw.ts#L212), which stores the value in a `BigInteger` even if the value is small enough to fit in a `Number`.

**Comment by wesboyt** [comment]
This would be addressed by use of a numbertower but probably wont be addressed till a v4 API.

**Comment by zslayton** [comment]
This was addressed as part of issue #663. The code was merged from PR #673, which includes nice benchmark results.
