### ISSUE TITLE
TextReader.next:  "Error:  invalid character 14 in string"

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-js#226]
Encountered when parsing the symbol `'\x0b\x0c\x0e'`:

"Error: invalid character 14 in string"
    at ParserTextRaw._read_string_helper  </Volumes/Unix/dev/ion/ion-hash-js/ion-bundle.js:4519:76>
    at ParserTextRaw._read_string1  </Volumes/Unix/dev/ion/ion-hash-js/ion-bundle.js:5072:17>
    at ParserTextRaw._read_value_helper_single  </Volumes/Unix/dev/ion/ion-hash-js/ion-bundle.js:4803:19>
    at ParserTextRaw._read_value_helper  </Volumes/Unix/dev/ion/ion-hash-js/ion-bundle.js:4726:23>
    at ParserTextRaw._read_value  </Volumes/Unix/dev/ion/ion-hash-js/ion-bundle.js:4710:17>
    at ParserTextRaw._run  </Volumes/Unix/dev/ion/ion-hash-js/ion-bundle.js:5650:19>
    at ParserTextRaw.next  </Volumes/Unix/dev/ion/ion-hash-js/ion-bundle.js:5630:21>
    at TextReader.next  </Volumes/Unix/dev/ion/ion-hash-js/ion-bundle.js:7139:35>

Same behavior if the symbol is being parsed as an annotation or fieldname.

**Comment by pbcornell** [comment]
The following code:
```javascript
let r = ion.makeReader("'\x0b\x0c\x0e'");
let t = r.next();
console.log(t.name);
console.log(r.value());
```
produces:
```
Error: invalid character 14 in string
    at ParserTextRaw._read_string_helper (dist/commonjs/es6/IonParserTextRaw.js:234:27)
    at ParserTextRaw._read_string1 (dist/commonjs/es6/IonParserTextRaw.js:757:14)
    at ParserTextRaw._read_value_helper_single (dist/commonjs/es6/IonParserTextRaw.js:494:16)
    at ParserTextRaw._read_value_helper (dist/commonjs/es6/IonParserTextRaw.js:424:20)
    at ParserTextRaw._read_value (dist/commonjs/es6/IonParserTextRaw.js:411:14)
    at ParserTextRaw._run (dist/commonjs/es6/IonParserTextRaw.js:1297:16)
    at ParserTextRaw.next (dist/commonjs/es6/IonParserTextRaw.js:1278:18)
    at TextReader.next (dist/commonjs/es6/IonTextReader.js:100:32)
    at Object.<anonymous> (tests/unit/tst-226.js:5:11)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```

**Comment by wesboyt** [comment]
let str = "'\\x0b\\x0c\\x0e'";
let r = ion.makeReader(str);
let t = r.next();
//console.log(t.name);symbol
console.log(r.value());
produces the correct tab \f escape output.

**Comment by zslayton** [comment]
[`IonParserTextRaw#is_valid_string_char()`](https://github.com/amzn/ion-js/blob/development/src/IonParserTextRaw.ts#L198) rejects any character with a numeric value less than 32, which bans a lot of legal-but-undisplayable control characters.

**Comment by zslayton** [comment]
As discussed offline, the parser's current behavior is correct.

```javascript
let r = ion.makeReader("'\x0b\x0c\x0e'");
let t = r.next();
console.log(t.name);
console.log(r.value());
```

Because the backslashes (`\`) in the input string `'\x0b\x0c\x0e'` are not themselves escaped, the Javascript string produced is the literal bytes `0b`, `0c`, `0e`. These bytes are not legal text Ion. Non-displayable ASCII characters (values < `0x20`) must be escaped. ([An issue](https://github.com/amzn/ion-docs/issues/76) has been opened to track clarifying this rule in the spec.)
