### ISSUE TITLE
TextReader.decimalValue:  "Error: Invalid integer"

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-js#227]
For values such as `-0d0` and `-0d-5`:

Error: Invalid integer: 
  at parseStringValue  <ion-bundle.js:1339:29>
  at parseValue  <ion-bundle.js:1367:20>
  at Integer  <ion-bundle.js:22:16>
  at new LongInt  <ion-bundle.js:4099:24>
  at Function.parse  <ion-bundle.js:2885:36>
  at TextReader.decimalValue  <ion-bundle.js:7983:41>
  at writeTo  <tests/IonHashTests.js:110:48>
  at toString  <tests/IonHashTests.js:159:9>
  at _loop_1  <tests/IonHashTests.js:174:22>
  at <tests/IonHashTests.js:207:9>

**Comment by wesboyt** [comment]
Decimal isn't in great shape on development branch theres going to be further refactoring/bugfixes.

**Comment by pbcornell** [comment]
The following code now behaves as expected; closing.

```javascript
let r = ion.makeReader("-0d0 -0d-5");
r.next();
console.log(r.value());
r.next();
console.log(r.value());
```

produces:
```
Decimal {
  _coefficient:
   LongInt { int: Integer { value: -0, sign: false, isSmall: true } },
  _exponent: 0 }
Decimal {
  _coefficient:
   LongInt { int: Integer { value: -0, sign: false, isSmall: true } },
  _exponent: -5 }
```
