### ISSUE TITLE
Writer was not at the top level, call closeContainer in the future (but there is no 'closeContainer' method)

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-js#229]
```javascript
let writer = ion.makeTextWriter();
writer.writeStruct();
writer.writeFieldName("a");
writer.writeInt(5);
writer.close();
```

produces:
```
Error: Writer was not at the top level, call closeContainer in the future.
  at TextWriter.close  <ion-bundle.js:8350:23>
  at <tests/IonHashTests.js:64:12>
  at Array.map  <anonymous>
```

However, the method `closeContainer` appears to have been renamed to `endContainer`.  Error message and method name should match.

**Comment by wesboyt** [comment]
This is a great issue, in binary we automatically close all open containers but in text we throw. We should fix this on the text side before v3 release.

**Comment by pbcornell** [comment]
Comment by wesboyt@ has been opened as a new issue https://github.com/amzn/ion-js/issues/259
