### ISSUE TITLE
IonWriter API provides two ways to write null values

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-js#255]
For example:
```javascript
writer.writeNull(TypeCode.STRING);
```
and
```javascript
writer.writeString(null);
```

Perhaps we should consider not allowing the latter?

See related issue #254

**Comment by zslayton** [comment]
Per offline discussion, closing this out to accommodate the use case where you're writing a `string` variable that may or may not be `null`.

```javascript
function writeSomeText(someText) {
    // `someText` could be a string, could be null
    writer.writeString(someText);
}
```

This differs from #254 in that there is no reasonable expectation that you can pass a complex container to a `write*` method and have it serialize correctly.
