### ISSUE TITLE
binary writer automatically closes any open containers;  text writer does not

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-js#259]
API behavior should be consistent for all writers.  To me, auto-closing open containers sounds like a mis-feature that could mask issues in the calling system.  It also seems to solve a problem that isn't much of a problem (how hard is it to write the code to explicitly close containers?).

This issue represents the following tasks:
1.  decide whether auto-closing is a feature that makes sense to have in this library
2.  make the behavior in binary and text writers consistent

**Comment by tgregg** [comment]
None of the other implementations that I'm familiar with automatically close containers when the writer is closed. They all throw if the user closes or finishes the writer below the top level. I suggest using the same behavior throughout ion-js for the reason cited by Peter: "auto-closing open containers sounds like a mis-feature that could mask issues in the calling system."

**Comment by pbcornell** [comment]
Resolved by #279, closing
