### ISSUE TITLE
timestamp:  add support for data model and instant equivalence

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-js#273]

**Comment by wesboyt** [comment]
The Date type held by the class allows us to compare up to the whole seconds. Then just compare the fraction Decimal.

**Comment by wesboyt** [comment]
Any two timestamps hold a JS Date(without any fractional seconds), we can use JS to compare  the two underlying Dates and then if they are equal compare the two underlying Decimal fractional seconds for equivalence.
