### ISSUE TITLE
eventstream failure:  good/testfile23.ion

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-js#283]
Error: Attempted to read an unsigned int that was larger than 31 bits. Use readUnsignedLongIntFrom instead. UInt size: 4, value: -294967296
at Function.readUnsignedIntFrom <src/IonParserBinaryRaw.ts:252:18>
at ParserBinaryRaw.readUnsignedInt <src/IonParserBinaryRaw.ts:265:31>
at ParserBinaryRaw.load_value <src/IonParserBinaryRaw.ts:465:38>
at ParserBinaryRaw.numberValue <src/IonParserBinaryRaw.ts:606:10>
at BinaryReader.numberValue <src/IonBinaryReader.ts:192:24>
at BinaryReader.value <src/IonBinaryReader.ts:225:20>
at IonEventStream.parseBinaryValue <src/IonEventStream.ts:401:26>
at IonEventStream.marshalEvent <src/IonEventStream.ts:275:51>
at IonEventStream.marshalStream <src/IonEventStream.ts:219:48>
at IonEventStream.generateStream <src/IonEventStream.ts:167:17>

**Comment by zslayton** [comment]
Related to #210.

**Comment by pbcornell** [comment]
good/testfile23.ion is no longer on the skiplist, closing
