### ISSUE TITLE
binary/text readers return different type for padded int

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-js#287]
Derived from `ion-tests/iontestdata/good/equivs/paddedInts.10n`.  Binary reader returns an IonLongInt object, while the text reader returns a number.  (maybe this is ok?)

```javascript
let ion = require("../../dist/commonjs/es6/Ion.js");

let bytes = new Uint8Array([
    0xe0, 0x01, 0x00, 0xea,
    0x2e, 0x90,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7f,
]);
getInt(bytes);

let tw = ion.makeTextWriter();
tw.writeInt(127);
tw.close();
getInt(tw.getBytes());

function getInt(src) {
    let r = ion.makeReader(src);
    r.next();
    let v = r.value();
    console.log(v + ', ' + typeof(v));
}
```

produces:
```
127, object         // an IonLongInt
127, number
```

**Comment by jonwilsdon** [comment]
Verify it is returning a JSBI object from both now.

**Comment by pbcornell** [comment]
I've verified that the above code receives a JSBI from both the binary and text reader's value() method (by adding `console.log(v)` after the shown `console.log()` statement.  Closing.
