### ISSUE TITLE
clarify IonDecimal.getDigits() and IonLongInt.digits() methods

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-js#298]
IonDecimal.getDigits() method currently returns the `_coefficient` property (why not call it getCoefficient()?).

IonLongInt.digits() returns a string.  We should aim for some form of consistency between these two methods.

Are there other *digit*() variants?

**Comment by wesboyt** [comment]
I think IonDecimal.getDigits() should be _getcoefficient() as we do not want to surface longint to the customer at this point in time.
IonLongInt.digits is attempting to differentiate itself from the full string representation and that could be clarified with a better name.

**Comment by pbcornell** [comment]
Decimal.getDigits() has been renamed to _getCoefficient(), and LongInt.digits() has been removed, as it is no longer used.
