### ISSUE TITLE
default valueType() inconsistent between text and binary

### ISSUE THREAD

**Issue by jonwilsdon** [amzn/ion-js#300]
With https://github.com/amzn/ion-js/pull/291, the default return value for `valueType()` in binary is now `null`. In text, the default return value for `valueType()` is `undefined`.

See: https://github.com/amzn/ion-js/blob/development/src/IonTextReader.ts#L66-L67

**Comment by pbcornell** [comment]
valueType() is not part of the Reader interface.  Related to #252

**Comment by pbcornell** [comment]
Resolved by #315, which adds a type() method to the Reader interface, and verifies consistent behavior across text and binary readers via the ReaderCompare test suite.  Closing.
