### ISSUE TITLE
define public API and mark the rest as internal

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-js#307]
TypeScript/JavaScript don't provide much support for declaring public vs. internal code.  Module systems (i.e., AMD or CommonJS) provide the notion of "export" (and everything else is internal), but a class is either exported or not--all methods of an exported class are exported along with the class.

The scope of this issue includes:
* reviewing the current public API and identifying what does/doesn't belong in that API
* making a best-effort to indicate (and enforce when possible) that everything not in the public API is internal.  This includes functions, classes, methods, and variables.
  * at a minimum, this involves prefixing such code with '_' to indicate _by convention_ that something is internal (for non-module environments)
  * in addition, where possible, a module system's export facility should be used to enforce the distinction between public and internal

Related to #299

**Comment by pbcornell** [comment]
The following are known API issues:
- remove the Writer.writeList/writeSexp/writeStruct isNull parameter (#254)
- Writer.writeNull(TypeCode) vs. Reader.next(): IonType (#309)
- IonLongInt is intended to be internal, but is exposed by Decimal.getDigits() (#310)
- clarify Decimal.getDigits() and LongInt.digits() (#298)
- provide some notion of internal vs. external (e.g., prefix internal classes/methods/properties/functions with '_') (currently also covered by this issue; perhaps should be split to another)
- IonEventStream.ts and IonEvent.ts don't belong in the src folder -- they are only for testing (#311)
- [fixed] reader.stringValue() previously returned a string representation for non-string/symbols (e.g., the string "null.<type>" or "5" for the int 5)
- [fixed] reader.numberValue() previously returned SIDs of symbols
- [fixed] various Reader \*value\*() methods previously returned `undefined`, but now returns `null`

The following are missing from the API:
- add Reader.type() (#252)
- utility function to transfer contents of a reader to a writer (#284)

**Comment by almann** [comment]
We really should consider having some first-class error type like `IonError` and have it prototype extend `Error`.  Since we're targeting ES6, this is pretty straightforward.

E.g.

```
class IonError extends Error {
  constructor(...args) {
    super(...args);
  }
}
```

These errors should be explicit, and we should support forms that allow for properties like `lineNumber` and `columnNumber` or the like.

**Comment by pbcornell** [comment]
Custom error classes is captured in #292.  Other items in this issue have been addressed, with the exception of '_' prefixing all internal artifacts;  public artifacts are in the generated documentation, all others are considered internal (as indicated by the v3.0.0 release notes).  Closing.
