### ISSUE TITLE
remove IonLongInt from public API

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-js#310]
This class is intended to be internal, but is currently exposed by Decimal.getValue() (and maybe other methods?)

**Comment by pbcornell** [comment]
#313 renamed Decimal.getValue() to _getCoefficient() (and thus "internal").  Are there other places where IonLongInt is exposed via the public API?

**Comment by pbcornell** [comment]
IonDecimal's constructor allows a LongInt to be passed; perhaps we can hide this?

**Comment by zslayton** [comment]
Fixed by #355.
