### ISSUE TITLE
Document API changes between the beta and the v3 release

### ISSUE THREAD

**Issue by jonwilsdon** [amzn/ion-js#316]
There are some backwards-incompatible changes for users of the beta version of the library that are coming in the v3 release. In order to help users update after the release, we should keep track of those changes and provide migration advice. This list is intended to be a list of changes that could affect users of the public APIs only.

**Note:** This issue is a work-in-progress.

Changes:
* `reader.value()` now throws for container types
  * PR with changes:  #291
  * _Migration_: use `reader.type()` to check the type before calling `reader.value()`

* `reader.valueType()` has been renamed to `reader.type()` and now returns `null` instead of `undefined`
  * PR with changes: #291, #315
  * _Migration_: change occurrences of  `reader.valueType()` to `reader.type()`
  * _Migration_: change occurrences of `reader.type() === undefined` to `reader.type() === null`

* `reader.numberValue()` has been made private and renamed to `reader._getSid()`
  * PR with changes: #291
  * _Migration_: None

* Decimal functions removed: `isZero()`, `isNegativeZero()`, `isZeroZero()`, `getNumber()`, `stringValue()`, `isNull()`, `lessThan()`, `greaterThan()`, `leq()`, `geq()`
  * PR with changes: #313
  * _Migration_: None

* Decimal functions made private and renamed: `getExponent()` to `_getExponent()` and `getDigits()` to `_getCoefficient()` 
  * PR with changes: #313
  * _Migration_: None

* `Decimal.compare()` changed to `Decimal.compareTo()`
  * PR with changes: #314
  * _Migration_: change occurrences of `compare()` to `compareTo()`

* Removed auto container close functionality from binary writer.
  * PR with changes: #279
  * _Migration_: after writing a container, call `writer.endContainer()` to close it

* `IonType` member field names changed for clarity, made `readonly`.
  * PR with changes: #397 
  * _Migration_: Update references to member fields of `IonType` instances as needed.

**Comment by jonwilsdon** [comment]
Todo: Add #337.

**Comment by jonwilsdon** [comment]
Todo: Add #355.

**Comment by pbcornell** [comment]
See [v3.0.0 release notes](https://github.com/amzn/ion-js/releases/tag/v3.0.0).
