### ISSUE TITLE
writer.writeInt(reader.numberValue(), 'a') should not work 

### ISSUE THREAD

**Issue by dblock** [amzn/ion-js#340]
Via https://github.com/amzn/ion-js/pull/319#discussion_r319165042

```
writer.writeInt(reader.numberValue(), 'a');
```

This shouldn't work at all, as the annotations parameter is supposed to be a `string[]`. Here 'a' is being treated as an array containing a single 1-character string (yay, javascript ;).

**Comment by pbcornell** [comment]
As another example:  `writer.writeInt(123, 'abc')` produces `a::b::c::123`.  This is a bug for all write*() methods, as well as stepIn().  Haven't investigated whether similar behavior exists in the binary or pretty-print writers.

**Comment by wesboyt** [comment]
should be a oneline fix: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray

**Comment by wesboyt** [comment]
merged
