### ISSUE TITLE
Unexpected precision/data loss when converting a decimal or large int to a number

### ISSUE THREAD

**Issue by zslayton** [amzn/ion-js#353]
According to the `big-integer` docs, the `toJSNumber` method [will silently lose precision](https://www.npmjs.com/package/big-integer#tojsnumber) for values outside of the range:`-9007199254740992` to `9007199254740992`, inclusive. This method is used in the implementations of both `LongInt#toNumber()` and `Decimal#toNumber()` (for the `Decimal`'s coefficient).

We should add a method that indicates whether a given `LongInt` or `Decimal` can be safely downgraded to a number before `toNumber()` is called.

**Comment by zslayton** [comment]
While `LongInt` has been removed, I believe that the current implementation of `Decimal#toNumber()` loses precision in a way that is inconsistent with the documented behavior. We should look into that discrepancy before closing this issue.

**Comment by pbcornell** [comment]
Given a string containing the number `12345678901234567890`, JavaScript's build-in parseInt() function returns the number `12345678901234567000`--loss of precision, but this is not unexpected.

However, given the same input, ion-js's `Reader.numberValue()` returns the number `9007199254740991`, which may as well be random number.  My expectation is for `numberValue()`'s behavior to align more closely with that of `parseInt()`.

Calls to clampToSafeIntegerRange() in IonParserBinaryRaw and IonParserTextRaw appear to be the culprit.  Consider using something like JSBI's `toNumber()` function instead.

**Comment by zslayton** [comment]
Fixed in #533.
