### ISSUE TITLE
Migrate from custom LongInt class to BigInt

### ISSUE THREAD

**Issue by zslayton** [amzn/ion-js#354]
Internally,`ion-js` uses a custom class called `LongInt` to represent integers larger than `(2^53)-1`. `LongInt` is a thin wrapper around a `big-integer.js`'s BigInteger, which is in turn a shim around [the new `BigInt` primitive](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt).

In order [to avoid users taking a dependency on the API offered by `LongInt`](https://github.com/amzn/ion-js/issues/310), we've removed support for Integers that [cannot be stored in 31 bits](https://github.com/amzn/ion-js/issues/210).

`BigInt` is [already supported](https://caniuse.com/#feat=bigint) in many popular JS runtimes--we may be able to migrate to it relatively soon depending on our runtime support requirements.

**Comment by almann** [comment]
I don't think we can directly support native `BigInt` without breaking ES5 compatibility (polyfilling this is apparently [hard](https://github.com/GoogleChromeLabs/jsbi#why)).  We should probably choose a `BigInt` object wrapper and expose that.

Some of the options

* [peterolson/BigInteger.js](https://github.com/peterolson/BigInteger.js) - the one we are presumably using currently.
* [GoogleChromeLabs/JSBI](https://github.com/GoogleChromeLabs/jsbi) - an implementation that is tracking the ECMAScript standard.

**Comment by nakedible** [comment]
I would definitely suggest using JSBI:

- Code matches native BigInt operations 1:1, so future translation is easy
- Can be transpiled to native BigInt by Babel for environments that support it today
- Very good performance
- Written by the Chrome team

In short, the closest you can get to a native BigInt today.

Unless you are willing to break ES5 compatibility, which would be my number one suggestion, in which case native BigInts would be great.

**Comment by zslayton** [comment]
Closed by #465, #469, and #470.
