### ISSUE TITLE
prevent private members from showing up in documentation

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-js#363]
I don't know whether this actually a problem, but suspect it is.  Ran across this, which may be helpful:  https://github.com/TypeStrong/typedoc/issues/506 (look for "tsd-is-private").

**Comment by zslayton** [comment]
The changes in PR #370 should keep methods and member fields marked `private` from being included in the docs. For other internal methods that can't be marked `private` (i.e. those that are prefixed with an `_`), you can add the `@hidden` annotation to the end of the TSDoc comment to suppress them.

```typescript
/**
 * This method isn't private.
 * @hidden
 */
 private _foo(bar: number): string {
 // ... 
 }
```
