### ISSUE TITLE
Add Doc Build Configuration to Prune Documentation to Public API

### ISSUE THREAD

**Issue by almann** [amzn/ion-js#369]
As per #365, we should also tighten the `typedoc` build to eliminate non-exported and internal APIs.

**Comment by wesboyt** [comment]
i was able to do so using @hidden on methods and adding files to the exclusion list within gruntfile.js

**Comment by almann** [comment]
@wesboyt - I used your example in the `Gruntfile.js` exclusion list in #370, but I was a bit more conservative with my patterns based on what I could reach from the `Ion` module.
