### ISSUE TITLE
Equivs/nonEquivs testing should include a roundtrip phase

### ISSUE THREAD

**Issue by zslayton** [amzn/ion-js#414]
In issue #408, the text and binary `Reader`s could distinguish between `0` and `-0` but the `Writer`s couldn't. This meant that simply reading the data in `ion-tests` was not enough to notice a problem, and round-tripping it produced the same (incorrect) values in both the text and binary files produced.

We should consider expanding our equivs/non-equivs tests to also roundtrip the data and make sure the tests still pass after the data has been serialized/deserialized.

**Comment by tgregg** [comment]
There is some discussion of this in the [ion-test-driver](https://github.com/amzn/ion-test-driver) README (for example, see [this section](https://github.com/amzn/ion-test-driver#goodnon-equivs-file-with-embedded-streams)). We should all review that document and determine whether anything is missing or unclear, or whether there is anything else that is present in the document but missing from the ion-js implementation.
