### ISSUE TITLE
NaN encoded incorrectly in text writer

### ISSUE THREAD

**Issue by nakedible** [amzn/ion-js#418]
https://github.com/amzn/ion-js/blob/43fce6d64dd326c0d73f0342f4769ec927588b1d/src/IonTextWriter.ts#L197-L198

In JavaScript, `NaN === NaN` is false. This needs to be either `Number.isNaN(value)` or `Object.is(value, Number.NaN)`. I would suggest the latter.

**Comment by almann** [comment]
Thanks for reporting this, I have incorporated the fix in #423, and I also agree that `Object.is(value, Number.NaN)` is the more consistent fix.
