### ISSUE TITLE
Decimal interface does not give access to coefficient and exponent

### ISSUE THREAD

**Issue by nakedible** [amzn/ion-js#419]
The `Decimal` interface does not give the user any access to the coefficient and exponent values. The only options are `intValue`, which truncates fractional portion and `numberValue` which is inexact. This means that it is impossible to accurately decipher `Decimal` values for any users.

Obviously BigNum issues should be solved first as both coefficient and exponent (theoretically) may be larger than what safely can be represented in a number.

**Comment by jonwilsdon** [comment]
Related to #354

**Comment by zslayton** [comment]
Closed by #469 and #470.
