### ISSUE TITLE
Decimal.toString often produces broken values

### ISSUE THREAD

**Issue by nakedible** [amzn/ion-js#420]
`Decimal.toString()` produces invalid values for many decimal values. For example, parsing `9007199254740991.000000` as text Ion and then calling `toDecimal()` on the result produces `9.0071992547409.91e+21`. Result for `3.000000000000000000000` is `3.e+21E-17`.

**Comment by dblock** [comment]
Those seem like valid values, and AFAIK ion-js you can read/write them both ways. Are you trying to read them with another parser and that fails?

**Comment by nakedible-p** [comment]
Valid values? Two dots in a single value? Two exponents in a single value? I don't think either is allowed by spec.

**Comment by wesboyt** [comment]
merged
