### ISSUE TITLE
Decimal does not expose any constructors for non-float values

### ISSUE THREAD

**Issue by nakedible** [amzn/ion-js#421]
Decimal class is supposed to be able to represent values outside the number type in JavaScript. However, the only public constructor takes coefficient and exponent as numbers, making it impossible to construct Decimal values where the coefficient does not fit in a JavaScript number.  There should be either string constructors, or BigNum support.

A current workaround is to use `Decimal.parse` and manually construct a string with both coefficient and exponent, delimited by `d`.

**Comment by wesboyt** [comment]
We decided not to make the longint (bigint wrapper) class part of the public api. Parse should fulfill your needs, we could make a parse from scientific notation function pretty easily.

**Comment by almann** [comment]
I believe #354 gets to the heart of this issue, once we have a formal large integer as part of our API, we can expose that for the components of the `Decimal` API for both constructing values and extracting those properties with full fidelity.

**Comment by nakedible** [comment]
Solved by #469 and #470.
