### ISSUE TITLE
No way to read integers larger than Number.MAX_SAFE_INTEGER

### ISSUE THREAD

**Issue by nakedible** [amzn/ion-js#422]
There is currently no public API in `Reader` to read integers that are larger than `Number.MAX_SAFE_INTEGER` or smaller than `Number.MIN_SAFE_INTEGER`. Even if no BigNum API were to be exposed, these could easily be represented as strings to allow at least some access to such values.

**Comment by almann** [comment]
#354 is probably the right long term fix for this issue, but barring that adding an API for the "text image" would probably be useful.  My question is would having a variant that returns the integer as a `string` representation be useful beyond fixing this with some kind of `BigInt` support?

**Comment by wesboyt** [comment]
the third option is making everything a number tower but would remove the user's ability to use numbers like numbers as typescript makes altering those prototypes impossible

**Comment by nakedible** [comment]
@almann I would say that even with BigInt support handled, it is useful to provide a "text image" for all types that cannot be trivially and losslessly represented in JavaScript. Even in the future, there are bound to be environments where BigInts are not convenient, and the base-10 string representation is useful for a lot of things even when real BitIntegers are not used.

**Comment by nakedible** [comment]
This is solved now in #465 and fix pulls after that.
