### ISSUE TITLE
Consider whether Ion JSON would be a worthwhile addition

### ISSUE THREAD

**Issue by nakedible** [amzn/ion-js#432]
I wrote a quick specification on how to translate Ion object in to JSON, and wrote a translator that uses `ion-js` to do this. I would appreciate it if someone could review this and consider if it would be a worthwhile addition to the Ion specifications, and perhaps even if it could be incorporated directly in to `ion-js`.

https://github.com/nakedible/ion-json/blob/master/SPECIFICATION.md

https://github.com/nakedible/ion-json

I know that personally I need this to sanely be able to work with Amazon QLDB documents using JavaScript, so somebody else might find it useful as well.

**Comment by dblock** [comment]
+1

I do this in a project currently with homegrown code. It's a lot easier to manipulate a JSON document in JavaScript to, for example, locate a node within the ion document then change a value or add a field. Our implementation completely ignores and fails annotations, so I am glad this spec addresses this in a bi-directional way.

**Comment by nakedible** [comment]
This belongs to https://github.com/amzn/ion-docs. I will re-raise it there after updating the specification a bit.
