### ISSUE TITLE
IonTextWriterTest relies on private isTopLevel accessor

### ISSUE THREAD

**Issue by zslayton** [amzn/ion-js#442]
`IonTextWriterTest` [uses the `isTopLevel` accessor](https://github.com/amzn/ion-js/blob/master/tests/unit/IonTextWriterTest.js#L32) that happens to be present on all implementations of `Writer` but which is not part of the `Writer` API.

This behavior works in Javascript but is (rightly) illegal in Typescript.

**Comment by pbcornell** [comment]
This was addressed by https://github.com/amzn/ion-js/pull/462, closing
