### ISSUE TITLE
IonAnnotationsTest relies on _writeValues

### ISSUE THREAD

**Issue by zslayton** [amzn/ion-js#454]
See [here](https://github.com/amzn/ion-js/blob/6fa07b4f5a820f28ee02e49fac4676a132559186/tests/unit/IonAnnotationsTest.js#L79). `_writeValues()` is not part of `Writer`'s public API.

**Comment by jonwilsdon** [comment]
Avoid adding the depth parameter to the public API.

**Comment by zslayton** [comment]
I reviewed `ion-java`'s implementation of `writeValues` to clarify the expected behavior of that method in `ion-js`. It performs [limited checks](https://github.com/amzn/ion-java/blob/master/src/com/amazon/ion/impl/bin/AbstractIonWriter.java#L90-L96) regarding the starting state of the reader and writer.

If a field name is set on the reader (which should only happen when it's inside a struct), the writer will attempt to set one if it is also inside a struct. If the writer is not positioned within a struct, the reader's field name will be ignored.

If a field name is not set on the reader but the writer IS in a struct, it will [throw an `IllegalStateException`](https://github.com/amzn/ion-java/blob/master/src/com/amazon/ion/impl/bin/IonRawBinaryWriter.java#L887-L890). 

Ideally I think there would be an early sanity check for the reader-not-in-struct+writer-in-struct use case, but that would require new APIs to be added to test `Reader#isInStruct()` from the `Writer` class. 

This could also be addressed by an addendum to [`IonWriter#writeValues()`' documentation](https://github.com/amzn/ion-java/blob/master/src/com/amazon/ion/IonWriter.java#L327-L340), which currently doesn't mention it.

**Comment by zslayton** [comment]
Fixed by PR #532
