### ISSUE TITLE
writeType(...) methods should not accept undefined

### ISSUE THREAD

**Issue by zslayton** [amzn/ion-js#456]
`Writer`'s `writeType` methods ([`writeTimestamp`](https://github.com/amzn/ion-js/blob/31871dc0e9404bef52037ae22c13d8aa49839362/src/IonBinaryWriter.ts#L236), [`writeString`](https://github.com/amzn/ion-js/blob/31871dc0e9404bef52037ae22c13d8aa49839362/src/IonBinaryWriter.ts#L214), etc) all accept `undefined` as a synonym for `null`. This means that calling `writeInt()` (with no parameters) produces `null.int`, which is rather surprising. Passing an `undefined` should probably cause an `Error` to be thrown.

**Comment by zslayton** [comment]
Related to #130, which is a much larger effort.

**Comment by pbcornell** [comment]
We've made an exception for `writeNull()`, which does not throw, and is equivalent to `writeNull(IonTypes.NULL)`
