### ISSUE TITLE
Flow control errors in ParserBinaryRaw#_stringRepresentation

### ISSUE THREAD

**Issue by zslayton** [amzn/ion-js#460]
There are multiple paths through `ParserBinaryRaw`'s `_stringRepresentation` method that can cause it to implicitly return `undefined`.

Examples:
* [Missing `return`](https://github.com/amzn/ion-js/blob/master/src/IonParserBinaryRaw.ts#L672)
* [Missing `break`](https://github.com/amzn/ion-js/blob/master/src/IonParserBinaryRaw.ts#L686)

We should add unit tests for this method.

**Comment by pbcornell** [comment]
It appears we may simply be able to remove `ParserBinaryRaw's` `_stringRepresentation` method.
