### ISSUE TITLE
how to make ion.makeReader with non-Engilsh content input in browser environment

### ISSUE THREAD

**Issue by junpengqiu** [amzn/ion-js#483]
Here is what I will get from HTML context making a reader on a single Chinese Character
```HTML
<script src="path/to/ion-bundle.min.js"></script>
<script>
var nonEngReader = ion.makeReader("子");
nonEngReader.next();
//Uncaught Error: unexpected character '23376'
//    at ParserTextRaw._done_with_error (ion-bundle.min.js:5803)
//    at ParserTextRaw._run (ion-bundle.min.js:6804)
//    at ParserTextRaw.next (ion-bundle.min.js:6779)
//    at TextReader.next (ion-bundle.min.js:8464)
//    at <anonymous>:1:3
</script>
```
However, it does work perfect in my nodejs env, so any suggestions on making ion-js able to read Japanese/Chinese in a web browser environment?

**Comment by wesboyt** [comment]
Hey Junpeng! If you make your input '"子"' or "'子'" it should work! "子" turns into just a string of 子 in memory in javascript which is not valid Ion.
子 by itself is an iontext symbol Identifier containing 子.
You need to surround it with single quotes to make "'子'" (an Ion quoted symbol) or '"子"' (an Ion string).
http://amzn.github.io/ion-docs/docs/symbols.html#symbol-representations

Locally I was unable to recreate a difference in node vs browser. 
"子" seems to be throwing as expected from this code:
`let reader = ion.makeReader("子");
reader.next();
console.log(reader.value());`
