### ISSUE TITLE
Mention that IonDecimal data model does not match specification data model

### ISSUE THREAD

**Issue by nakedible** [amzn/ion-js#498]
This is what is in source code:

https://github.com/amzn/ion-js/blob/475134c145b5a9250d399fe6e9161d88d19f3f55/src/IonDecimal.ts#L44-L48

And this is what is in the referenced Ion Decimal documentation:

> Ion decimals follow the IBM Hursley Lab General Decimal Arithmetic Specification, which defines an abstract decimal data model represented by the following 3-tuple.
> 
> (<sign 0|1>, <coefficient: unsigned integer>, <exponent: integer>)

The difference here is that in Ion Decimal documentation, the coefficient is an unsigned integer and hence always positive, where as in this library, the coefficient is signed. If the value is negative, then `getCoefficient()` will also return a negative value. Indeed, the only reason for the sign field is to support `-0` here.

It doesn't really matter either way, but I think a small note on the difference in representation should be added here to lessen the confusion.

**Comment by zslayton** [comment]
Addressed by #500
