### ISSUE TITLE
Reader `next` returns a value of `IonType` which seems to be an internal data definition.

### ISSUE THREAD

**Issue by therapon** [amzn/ion-js#50]
Using [`Reader.next()`](https://amzn.github.io/ion-js/api/interfaces/_ionreader_.reader.html#next) on Ion Data currently returns a value of type [`IonType`](https://amzn.github.io/ion-js/api/classes/_iontype_.iontype.html). 

The return value seems internal to me. What should (or could) a client do with a value of `IonType`?

**Comment by wesboyt** [comment]
IonType tells you what type the parser interpreted the next ionvalue as having. Allowing the user to choose what functionality/tovalue logic is available to them.
