### ISSUE TITLE
Consumer's guide for reconciling multiple sources of our library.

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#501]
Currently when a use case generates readers and writers from more than one ion.js file object comparisons fail when the two interact.
We have two paths:
-Remove all object equivalence/switch case logic that relies on object reference equivalence and instead use enum/int lookups.
-Investigate and document how users/consumers should reconcile their build process other than npm which can use peer dependency to reconcile multiple ion dependencies.

**Comment by pbcornell** [comment]
Add a comment/warning to README.md; no code changes planned
