### ISSUE TITLE
Provide translations from/to JSON

### ISSUE THREAD

**Issue by therapon** [amzn/ion-js#52]
Even though there is data loss when translating from Ion to JSON, the ability to do so seems to be a good feature to have here. So adding operations that will allow 

* JSON->Ion 
* Ion ->JSON 

as part of the API would be nice.

**Comment by ygnr** [comment]
It would be nice to have this feature or do you suggest any alternative when you have to convert the data to JSON?

**Comment by tgregg** [comment]
Note to anyone considering implementing this feature: the JSON down-conversion rules that should be followed are listed in the cookbook: http://amzn.github.io/ion-docs/guides/cookbook.html#down-converting-to-json

**Comment by KotoJallow** [comment]
@therapon if the feature is not available, check this out
https://github.com/KotoJallow/IonToJson
ion -> json
I hope it helps

**Comment by zslayton** [comment]
Related: #563

**Comment by zslayton** [comment]
Addressed by #563.
