### ISSUE TITLE
Question: Get array value?

### ISSUE THREAD

**Issue by jfuehner** [amzn/ion-js#556]
Sorry, new to ion and its api. Looking for some assistance...

Assuming I have a object that looks like...

```
{
     data: [
        {id: 1, name: 'test'},
        {id:2, name: 'test2'}
     ]
}
```

Does ion have a way to get the entire array value and all items back... Or will I need to walk through each array item? I'm not seeing anything in the docs that walks through such an example. 

Any assistance would be great! Are there plans to evolve the javascript api to make it easier to extract data?

**Comment by zslayton** [comment]
Hi! 
> Does ion have a way to get the entire array value and all items back... Or will I need to walk through each array item?

Currently you would need to walk through each array item via `stepIn()` and `next()`. Keep an eye on issue #531, however, as we hope to have a more ergonomic solution available soon.
