### ISSUE TITLE
Add an equals() method to the dom.Value interface

### ISSUE THREAD

**Issue by zslayton** [amzn/ion-js#576]
The tests in `test/dom` do lots of ad-hoc equality testing between `dom.Value` instances. We should provide a sensible out-of-the-box solution. Implementations of `equals()` for container types should be recursive.

**Comment by MFornander** [comment]
Yes please!  Was using ion-js for a few days to prototype some things before moving to ion-c but without a working equals(), it makes it so hard.

Taking from:
https://github.com/amzn/ion-js/blob/master/src/dom/README.md#iondom-data-types

Please make this pass:
assert.equal(ionString, ionString2);

**Comment by zslayton** [comment]
This functionality was merged in PR #669 and will be included in the next release.

> Please make this pass:
> assert.equal(ionString, ionString2);

Unfortunately there's no way to override the equality test that's being used in `assert.equal`, but this will work:
```typescript
assert.isTrue(ionString.equals(ionString2));
```
