### ISSUE TITLE
Question: DOM Api load eager/lazy?

### ISSUE THREAD

**Issue by jfuehner** [amzn/ion-js#594]
@zslayton I was looking over the to-be-released [DOM API documentation](https://github.com/amzn/ion-js/blob/zslayton-dom-readme/src/dom/README.md). I have a number of Java backend micro-services where I'd like to serialize objects and send them down to our clients as `arraybuffer`'s and then utilize them as ion-js objects client-side. The objects that get passed down from the services can be rather large.

Does the `load` function eagerly load the entire object or are values loaded lazily upon being accessed? Would you have any benchmarks available with regards to working with large objects?

Any ETA when the DOM API will be available?

**Comment by zslayton** [comment]
> Does the load function eagerly load the entire object or are values loaded lazily upon being accessed?

`ion.load()` will eagerly load the first value it encounters in the provided `Reader` or serialized data source. (Compare this to `ion.loadAll()`, which will eagerly load *all* of the values in the data source.)

However, if you wish to only load one or more portions of a very large object, you could do this by creating a `Reader`, navigating to the desired nested value, and then passing the reader to `ion.load()`, like so:

```javascript
// "..." used here to represent very large subdocuments
let data = ' { foo: [...], bar: {...}, baz: {...}} ';
let reader = ion.makeReader(data);
reader.next();
reader.stepIn();
while (reader.fieldName() !== "baz") {
  reader.next();
}
let baz = ion.load(reader);
```
*Disclaimer: This example should work but I didn't test it. :)*

> Would you have any benchmarks available with regards to working with large objects?

There aren't currently any benchmarks available, sorry. If you encounter any performance problems, please let me know by opening an issue with one or more examples.

> Any ETA when the DOM API will be available?

I can't commit to a particular date, but it should be quite soon.

**Comment by zslayton** [comment]
Hopefully this answered your question. I'm going to close this issue for bookkeeping reasons. Feel free to re-open it if you need more information.

**Comment by zslayton** [comment]
> Any ETA when the DOM API will be available?

[Version 4.0.0](https://github.com/amzn/ion-js/releases/tag/v4.0.0) has been released.
