### ISSUE TITLE
Nested ArrayBuffer Within Ion Object?

### ISSUE THREAD

**Issue by jfuehner** [amzn/ion-js#612]
Hi! Was curious if it is possible to nest an ArrayBuffer or TypedArray within an Ion object? 

As an example, say I have an object structure such as...
```
{
     id: 1234,
     children: TypedArray or ArrayBuffer
}
```

If I were to convert the structure to/from an Ion object would it maintain the TypedArray or ArrayBuffer type for the `children` property in the structure? Or... Would it get converted to standard array such as how JSON.parse/stringify works?

**Comment by zslayton** [comment]
If `children` is a `Uint8Array` specifically, it would be turned into a `Blob`. Any other instance of `Array` would be turned into a `List`. It's possible we could broaden it from `Uint8Array` to `TypedArray`/`ArrayBuffer` with some thought, but we haven't had a use case for it.

Here's [the relevant source](https://github.com/amzn/ion-js/blob/9a74c382c3f9c7743423a83539055df509f61828/src/dom/JsValueConversion.ts#L131-L136) if you're interested.
