### ISSUE TITLE
Add support for deleting a key in Struct

### ISSUE THREAD

**Issue by alexis779** [amzn/ion-js#622]
There is no **delete** method in [Struct](https://amzn.github.io/ion-js/api/classes/_dom_struct_.struct.html) class.

To delete a Struct key, I run those steps:

- parse ION
- convert to JSON
- delete key on Object
- convert back to ION

_test_ion_struct_delete_key.js_ content:
```Javascript
const ion = require('ion-js');

var ionStr = '[ { key: "value" } ]';
console.log(ionStr);

const list = ion.load(ionStr);

var struct = list[0];
struct = JSON.parse(JSON.stringify(struct))
delete struct['key'];
list[0] = ion.load(JSON.stringify(struct))

ionStr = ion.dumpText(list);
console.log(ionStr);
```

Output:
```
$ node test_ion_struct_delete_key.js
[ { key: "value" } ]
[{}]
```

**Comment by zslayton** [comment]
Addressed in #623.
