### ISSUE TITLE
Timestamp seems to incorrectly interprete the timezone

### ISSUE THREAD

**Issue by kadishmal** [amzn/ion-js#64]
- The record has a timestamp field `startDate = 1498415400000`.
- This is `GMT: Sunday, June 25, 2017 6:30:00 PM`.
- When creating an ion struct in Java, a corresponding field was added that reflects the timezone like `start_date:2017-06-26T00:00:00.000+05:30`

1. The problem is that when reading this value with `ion-js`, the `stringValue()` produces an incorrect mixed date value `2017-06-25T18:30:0.0+05:30` which is neither the UTC nor the locatime.
2. Also notice how seconds are formatted. They should be `00.000` instead of `0.0`.

**Comment by pbcornell** [comment]
Verify whether this is still an issue prior to v3 release

**Comment by pbcornell** [comment]
The issues identified above are addressed with the latest changes on the development branch.

The following code:
```javascript
let dateStr = new Date(1498415400000).toISOString();
let ts = ion.Timestamp.parse(dateStr);
let writer = ion.makeTextWriter();
writer.writeTimestamp(ts);
writer.close();

console.log('    dateStr: ' + dateStr);
console.log('  timestamp: ' + ts.toString());
console.log('text writer: ' + String.fromCharCode.apply(null, writer.getBytes()));
```

now produces:
```
    dateStr: 2017-06-25T18:30:00.000Z
  timestamp: 2017-06-25T18:30:00.000Z
text writer: 2017-06-25T18:30:00.000Z
```

(note also that Timestamp's `stringValue()` method has been renamed to `toString()`)
