### ISSUE TITLE
Add getPosition() function to Reader

### ISSUE THREAD

**Issue by bingkh** [amzn/ion-js#654]
Hi, 

**Description**
As a user of ion-js, I would love to be able to get position information from ionReader, so that when using ionReader to read a ion file, I can know which position I'm currently at.

**Application scenario**
Our team uses ion to define a format, e.g. paragraph `P` uses certain format style `S`, and the definition of style `S` is out side of the paragraph itself. see blow:
```
style::{
  name:S,
  font:Arial,
  .....
}
....
....
paragraph::{
  name:A,
  style:S,
  .....
}
```
I'm working on a vs code extension: ion-style-peek, so that in the above ion file, when users are viewing paragraph `A` and call `go to definition` on `S`, the editor will jump to style `S`.  Similar implementation can be found: https://github.com/pranaygp/vscode-css-peek

To implement the above, we need to get the position when parsing style container in the ion, hence the requesting issue.

Pull request:
https://github.com/amzn/ion-js/pull/655

Thanks!

Ethan

**Comment by zslayton** [comment]
Added in #657.
