### ISSUE TITLE
Store smaller integers as numbers instead of BigInts

### ISSUE THREAD

**Issue by desaikd** [amzn/ion-js#663]
*Description:*
Using `number` for smaller integers instead of `JSBI.BigInt` could be  a helpful useful performance change (which can potentially be providing 20% speed up)

*Performance change:*
Instead of using [`JSBI.BigInt`](https://github.com/GoogleChromeLabs/jsbi#usage) for all the Signed Integers we can use native `number` datatype for values less than [5 bytes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger). This will speed up the performance because it saves the time of converting `JSBI.BIgInt` into `number`.

Here's the result of improvement in performance using [benchmarkjs](https://benchmarkjs.com) for measurement.
```
Using JSBI.BigInt for smaller no of bytes:
10.172569152600001
Binary Reader Large x 0.10 ops/sec ±1.86% (5 runs sampled)

Using number for smaller no of bytes:
8.447150749799999
Binary Reader Large x 0.12 ops/sec ±1.63% (5 runs sampled)
```
The threshold used here is 5 bytes. The results show that this change could improve the speed up to 20%. but this change would have some requirements to be addressed as described below.

*Requirements for the performance change to be implemented:*

- Add a warning to the already-deprecated `.value()` method explaining that two values with the same Ion type can have two different JS type representations. (e.g. `number` and `jsbi` for Ion’s `int`). This will require people to use `numberValue()`  and `bigIntValue()` instead of `value()`.

- Provide an `equals` method on `dom.Value` API and let people use that instead. (This can also be used for test suites in ion-js).

*Some related issues addressing this concern:*

- #576: regarding the having an `equals` method on `dom.Value`.
- #218: regarding the performance improvement using `number`.

**Comment by zslayton** [comment]
This optimization was merged in PR #673, which includes some nice benchmark results. 👌
