### ISSUE TITLE
Release version ES6 is a CommonJS module

### ISSUE THREAD

**Issue by ColinTimBarndt** [amzn/ion-js#667]
Referring to release [v4.1.0](https://github.com/amzn/ion-js/tree/v4.1.0):

There are 4 versions of the release: `amd`, `browser`, `commonjs` and `es6`. An [ES6 module](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) uses import and export statements where a commonjs module uses require() and exports. In v4.1.0, the ES6 module release is actually a commonjs build. Importing `Ion.js` as a module results in the following error:

```txt
Uncaught ReferenceError: exports is not defined
    <anonymous> http://127.0.0.1:5500/js/ion/Ion.js:38
Ion.js:38:1
```

```js
// Line 38
Object.defineProperty(exports, "__esModule", { value: true });
```

```js
import * as ion from "./js/ion/Ion.js";
```

**Comment by desaikd** [comment]
Thanks @ColinTimBarndt for bringing this to our attention. We are currently working on this issue.

**Comment by desaikd** [comment]
Modified tsconfig to generate the ES6 module in right way.
