### ISSUE TITLE
Timestamp enhacements 

### ISSUE THREAD

**Issue by chafey** [amzn/ion-js#675]
Timestamp currently requires that you specify each component (offset, year, month, day, hour, minute, second).  A common use case is to create a Timestamp for now or based on an existing Date.  It would be nice if there were convenience functions for both.  Here is some code I wrote for now():

https://github.com/chafey/dicom2ion-js/blob/main/src/timestampNow.js

I would be happy to submit a PR if this is this functionality is desired

**Comment by desaikd** [comment]
This looks like a good change to have for `ion-js`. Your change looks good although we would like to use a multi-constructor approach here, something like we have used in [`ion.Decimal`](https://github.com/amzn/ion-js/blob/master/src/IonDecimal.ts#L85) class. Currently the class that takes all the (offset, year, month, day, hour, minute, second) components to create a Timestamp is [`ion.Timestamp`](https://github.com/amzn/ion-js/blob/master/src/IonTimestamp.ts#L73-L80), where you can add your change and submit a PR.

**Comment by chafey** [comment]
Thank you for the quick response, I'll start working on this now.

**Comment by chafey** [comment]
I decided to create a static factory method as the constructor was already getting pretty long and unwieldy - hope thats OK!  If not, I can resubmit with overloaded constructor.  Thanks

**Comment by desaikd** [comment]
PR #686 contains changes for creating `Timestamp` using `Date` object.
