### ISSUE TITLE
Struct does not support "repeated fields"

### ISSUE THREAD

**Issue by fnmdx111** [amzn/ion-js#676]
Ion specification says

> When two fields in the same struct have the same name we say there are “repeated names” or (somewhat misleadingly) “repeated fields”. Implementations must preserve all such fields, i.e., they may not discard fields that have repeated names. [1]

But ion-js does not support repeated fields, I always get the last value for the repeated fields. This is also seen in the implementation here (https://github.com/amzn/ion-js/blob/master/src/dom/Struct.ts#L44-L48).

Please make sure ion-js lives up to Ion spec. Thank you!

[1] https://amzn.github.io/ion-docs/docs/spec.html#struct

**Comment by zslayton** [comment]
We're aware of this limitation and intend to address it in the next release of `ion-js`.

**Comment by fnmdx111** [comment]
Thanks for the confirmation. Do you have a date for that release?

**Comment by zslayton** [comment]
That release is not scheduled yet, but should be relatively soon.

**Comment by desaikd** [comment]
We have added support for repeated fields with https://github.com/amzn/ion-js/pull/679. Please try it out and let us know if you have any issues with this change.

**Comment by fnmdx111** [comment]
Thanks, I'll try it out in a few days.

**Comment by fnmdx111** [comment]
Hello there. I tried it out and I think it's working fine with my test data. Thanks for the fix.

When can I expect this to be published to NPM?

**Comment by desaikd** [comment]
Thanks for trying out the change. We are working on the new release.

**Comment by desaikd** [comment]
`ion-js` 4.2.1 has been released with all the changes requested here.
