### ISSUE TITLE
Object.assign pollyfill for ES5 support

### ISSUE THREAD

**Issue by therapon** [amzn/ion-js#69]
It appears that the current process of ES6->ES5 does not deal with `Object.assign` 

To repro 

1. Run `jjs` 
1. load("https://amzn.github.io/ion-js/browser/scripts/ion-bundle.js") 

Thows 
`https://amzn.github.io/ion-js/browser/scripts/ion-bundle.js:5481 TypeError: Object.assign is not a function` 

Try the corresponding polyfill 
https://www.npmjs.com/package/babel-plugin-transform-object-assign

**Comment by dhan-vijay** [comment]
I have gotten around with a temp fix @5487

exports.StringEscapes = JSON.parse(JSON.stringify(CommonEscapes)); //Object['assign']({}, CommonEscapes);
exports.StringEscapes[CharCodes.DOUBLE_QUOTE] = backslashEscape('"');
exports.SymbolEscapes = JSON.parse(JSON.stringify(CommonEscapes));; //Object['assign']({}, CommonEscapes);

**Comment by therapon** [comment]
Updated the our build process to re-write the `Object.assign` using the babel plugin. 
Tested using `jjs` here is the output from my terminal 

```
> jjs                                                  ~/IonJS 
jjs> load("https://amzn.github.io/ion-js/browser/scripts/ion-bundle.js")
jjs> this.ion
[object Object]
jjs> var ionData = "{ hello: \"Ion\" }"; 
jjs> var r = this.ion.makeReader(ionData); 
jjs> r.next()
[object Object]
jjs> r.stepIn()
jjs> r.next()
[object Object]
jjs> var h = r.fieldName()
jjs> var i = r.stringValue()
jjs> h
hello
jjs> i
Ion
jjs> 
```
