### ISSUE TITLE
`IonReader.bigIntValue()` does not always return JSBI values when reading Ion binary

### ISSUE THREAD

**Issue by YourFin** [amzn/ion-js#709]
In the process of testing my own code, I noticed that [`IonReader.bigIntValue()`](https://amzn.github.io/ion-js/api/interfaces/_ionreader_.reader.html#bigintvalue) was sometimes returning `number` values, contrary to its contract of only returning JSBI instances or null. Further testing revealed that this only occurred when reading binary data. A minimal failing test case can be found in my fork of this repository here: https://github.com/YourFin/ion-js/commit/03a85a3854a9f5d8457c41e7d011a0fc5e332037

Some spelunking revealed that this is likely a regression introduced by https://github.com/amzn/ion-js/commit/3554f29b438fbc7021cf3760a46775257514be1d, as following the call stack down reveals that `.bigIntValue()` returns [the `any`-typed `_curr` value](https://github.com/amzn/ion-js/blob/6f3ef1670557c410ca8e627696079ca6264d7e90/src/IonParserBinaryRaw.ts#L133) on the underlying `ParserBinaryRaw`. Prior to https://github.com/amzn/ion-js/commit/3554f29b438fbc7021cf3760a46775257514be1d, when `_curr` was updated by [`_readIntegerMagnitude`](https://github.com/amzn/ion-js/commit/3554f29b438fbc7021cf3760a46775257514be1d#diff-efaccdda66ff99d413445232e7630c33a3487359b088b2f95a41a9bb37c198eeR784) (via [`IonParserBinaryRaw.bigIntValue`](https://github.com/amzn/ion-js/blob/6f3ef1670557c410ca8e627696079ca6264d7e90/src/IonParserBinaryRaw.ts#L474) -> [`IonParserBinaryRaw.load_value`](https://github.com/amzn/ion-js/blob/6f3ef1670557c410ca8e627696079ca6264d7e90/src/IonParserBinaryRaw.ts#L805)) it could only be set to JSBI values, but following the commit it could be set to JSBI or `number` values.

I have [what appears to be a fix for this issue](https://github.com/YourFin/ion-js/commit/82c9a437fed8aee63c7d025a17e70552efdeb97e) committed to my fork of this repository; let me know (slack nuckolp@) if you'd like me to cut that as a pr.

**Comment by popematt** [comment]
Hi Patrick, thanks for letting us know about this problem. We would gladly accept a PR to fix it.

**Comment by YourFin** [comment]
Closing this issue as the fix was merged
