### ISSUE TITLE
Text reader doesn't accept byte arrays of text anymore

### ISSUE THREAD

**Issue by mtcalvin** [amzn/ion-js#77]
I'm unsure if this is a regression or if it was never intended behavior in the first place.

Previously, passing text data as a byte array to `makeReader` would still return a functioning text reader.  Now it throws an error:

```js
var ionJs = require("ion-js")
var input = "{foo:bar}";
var arr = new Uint8Array(input.length)
// A more realistic example would be loading a text file from disk as a Buffer (node.js) or Blob (HTML5)
for (var i = 0; i < input.length; i++) arr[i] = input.charCodeAt(i)

var reader = ionJs.makeReader(arr);
console.log(reader.next().name);
```

```
TypeError: this._src.charCodeAt is not a function
```

2.0.0: https://runkit.com/embed/vz9xv8h87vqp
2.1.2: https://runkit.com/embed/ee8ubusq2qrx (contains more detailed stack trace)

**Comment by wesboyt** [comment]
fixed in: fd49bc809f35dad7e700d7d86b4bd6e4af45412a
